replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-2.amazonaws.com/totem-core-explorer-backend 
  pullPolicy: Always
  tag: "prod"

fullnameOverride: "totem-core-explorer-backend"
containerPort: 50051

ingress:
  enabled: false
  annotations:
    {}
service:
  type: NodePort
  port: 50051
  protocol: TCP
  targetPort: 50051

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownSeconds: 3

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

env:
   ENV: ""

