apiVersion: v1
kind: Service
metadata:
  labels:
    app: core-explorer-backend
  name: core-explorer-backend
spec:
  selector:
    app: core-explorer-backend
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
